version: "3.9"

services:
  db:
    container_name: data
    image: postgres:15.3
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: always

  api:
    container_name: api
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${API_PORT}:8080
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/api/system/health | grep true || exit 1"
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: always